export enum WXBgs {
  CLEAR = 'clear',
  ClearNight = 'clear_night',
  MOSTLY_CLEAR = 'mostly_clear',
  MostlyClearNight = 'mostly_clear_night',
  PARTLY_CLEAR = 'partly_clear',
  CLOUDY = 'cloudy',
  CloudyNight = 'cloudy_night',
  PARTLY_CLOUDY = 'partly_cloudy',
  PartlyCloudyNight = 'partly_cloudy_night',
  MOSTLY_CLOUDY = 'mostly_cloudy',
  CLOUDY_RAIN = 'cloudy_rain',
  PARTLY_CLOUDY_WITH_OCCASIONAL_SHOWERS_OR_THUNDERSHOWERS = 'partly_cloudy_with_occational_showers_or_thundershowers',
  MOSTLY_CLOUDY_WITH_OCCASIONAL_SHOWERS = 'mostly_cloudy_with_occational_showers',
  CLOUD_WITH_THUNDERSTORMS = 'cloud_with_thunder_storm',
  Temp_Rain = 'temp_rain',
  OCCASIONAL_SHOWERS_OR_THUNDERSTORMS = 'mostly_cloudy_with_occational_showers',
  OCCASIONAL_AFTERNOON_THUNDERSHOWERS = '',
}
