export enum WXIcons {
  Clear_Sunny = 'clear_sunny',
  Mostly_Clear = 'mostly_clear',
  Partly_Clear = 'partly_clear',
  Sunny_Big_Cloud = 'sunny_big_cloud',
  Sunny_Cloud = 'sunny_cloud',
  CLOUD = 'cloud',
  CLOUDY = 'cloudy',
  Two_White_Cloud = '2_white_cloud',
  Cloud_Thunder_Shower = 'cloud_thunder_shower',
  Cloudy_Shower = 'cloudy_shower',
  Cloud_Shower = 'cloud_shower',
  Thunder_Storm_Shower_Afternoon = 'thunder_storm_shower_afternoon',
  Cloudy_Thunder_Storm_Shower_Afternoon = 'cloudy_thunder_storm_shower_afternoon',
  // PARTLY_CLOUDY_WITH_OCCASIONAL_AFTERNOON_THUNDERSHOWERS = '',
  // OCCASIONAL_SHOWERS_OR_THUNDERSTORMS = '',
  // OCCASIONAL_AFTERNOON_THUNDERSHOWERS = '',
};
